package com.example.ggd;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;

public class StationInfo {
    @SerializedName("stationList")
    @Expose
    ArrayList<Station> stationList;

    class Station {
        @SerializedName("statnNm")
        @Expose
        String statnNm;
        @SerializedName("subwayNm")
        @Expose
        String subwayNm;
    }
}

/*

{
    "stationList": [
        {
            "beginRow": null,
            "endRow": null,
            "curPage": null,
            "pageRow": null,
            "totalCount": 10,
            "rowNum": 1,
            "selectedCount": 5,
            "statnId": "1006000640",
            "statnNm": "고려대",
            "subwayId": "1006",
            "subwayNm": "6호선",
            "statnNmEng": null,
            "statnFid": null,
            "statnFnm": null,
            "statnTid": null,
            "statnTnm": null,
            "operPblinstt": null,
            "zipNo": null,
            "adresBass": null,
            "adresDetail": null,
            "telno": null,
            "fxnum": null,
            "directAt": null,
            "ord": "1",
            "subwayXcnts": "203204.85374",
            "subwayYcnts": "454576.17819",
            "trnsitCo": null,
            "subwayList": null,
            "pltfomSe": null,
            "gffDoor": null,
            "crosngAt": null,
            "toiletAt": null,
            "dspsnCvntlAt": null,
            "trttprkAt": null,
            "bcyclCstdyAt": null,
            "sctnTime": null,
            "sctnDstnc": null,
            "statnSn": null,
            "updnLine": null,
            "trainSttus": null,
            "lstcarAt": null,
            "imageX": "1613",
            "imageY": "477",
            "trainNo": null,
            "lastRecptnDt": null,
            "fixedDateTimeStr": null
        },
        {
            "beginRow": null,
            "endRow": null,
            "curPage": null,
            "pageRow": null,
            "totalCount": 10,
            "rowNum": 2,
            "selectedCount": 5,
            "statnId": "1006000639",
            "statnNm": "안암",
            "subwayId": "1006",
            "subwayNm": "6호선",
            "statnNmEng": null,
            "statnFid": null,
            "statnFnm": null,
            "statnTid": null,
            "statnTnm": null,
            "operPblinstt": null,
            "zipNo": null,
            "adresBass": null,
            "adresDetail": null,
            "telno": null,
            "fxnum": null,
            "directAt": null,
            "ord": "2",
            "subwayXcnts": "202580.62087",
            "subwayYcnts": "454093.92888",
            "trnsitCo": null,
            "subwayList": null,
            "pltfomSe": null,
            "gffDoor": null,
            "crosngAt": null,
            "toiletAt": null,
            "dspsnCvntlAt": null,
            "trttprkAt": null,
            "bcyclCstdyAt": null,
            "sctnTime": null,
            "sctnDstnc": null,
            "statnSn": null,
            "updnLine": null,
            "trainSttus": null,
            "lstcarAt": null,
            "imageX": "1578",
            "imageY": "512",
            "trainNo": null,
            "lastRecptnDt": null,
            "fixedDateTimeStr": null
        },
        {
            "beginRow": null,
            "endRow": null,
            "curPage": null,
            "pageRow": null,
            "totalCount": 10,
            "rowNum": 3,
            "selectedCount": 5,
            "statnId": "1001000124",
            "statnNm": "청량리",
            "subwayId": "1001",
            "subwayNm": "1호선",
            "statnNmEng": null,
            "statnFid": null,
            "statnFnm": null,
            "statnTid": null,
            "statnTnm": null,
            "operPblinstt": null,
            "zipNo": null,
            "adresBass": null,
            "adresDetail": null,
            "telno": null,
            "fxnum": null,
            "directAt": null,
            "ord": "3",
            "subwayXcnts": "203979.7944",
            "subwayYcnts": "453425.90031",
            "trnsitCo": null,
            "subwayList": null,
            "pltfomSe": null,
            "gffDoor": null,
            "crosngAt": null,
            "toiletAt": null,
            "dspsnCvntlAt": null,
            "trttprkAt": null,
            "bcyclCstdyAt": null,
            "sctnTime": null,
            "sctnDstnc": null,
            "statnSn": null,
            "updnLine": null,
            "trainSttus": null,
            "lstcarAt": null,
            "imageX": "1767",
            "imageY": "668",
            "trainNo": null,
            "lastRecptnDt": null,
            "fixedDateTimeStr": null
        },
        {
            "beginRow": null,
            "endRow": null,
            "curPage": null,
            "pageRow": null,
            "totalCount": 10,
            "rowNum": 4,
            "selectedCount": 5,
            "statnId": "1001000125",
            "statnNm": "제기동",
            "subwayId": "1001",
            "subwayNm": "1호선",
            "statnNmEng": null,
            "statnFid": null,
            "statnFnm": null,
            "statnTid": null,
            "statnTnm": null,
            "operPblinstt": null,
            "zipNo": null,
            "adresBass": null,
            "adresDetail": null,
            "telno": null,
            "fxnum": null,
            "directAt": null,
            "ord": "4",
            "subwayXcnts": "203067.02818",
            "subwayYcnts": "453197.59138",
            "trnsitCo": null,
            "subwayList": null,
            "pltfomSe": null,
            "gffDoor": null,
            "crosngAt": null,
            "toiletAt": null,
            "dspsnCvntlAt": null,
            "trttprkAt": null,
            "bcyclCstdyAt": null,
            "sctnTime": null,
            "sctnDstnc": null,
            "statnSn": null,
            "updnLine": null,
            "trainSttus": null,
            "lstcarAt": null,
            "imageX": "1696",
            "imageY": "684",
            "trainNo": null,
            "lastRecptnDt": null,
            "fixedDateTimeStr": null
        },
        {
            "beginRow": null,
            "endRow": null,
            "curPage": null,
            "pageRow": null,
            "totalCount": 10,
            "rowNum": 5,
            "selectedCount": 5,
            "statnId": "1063075117",
            "statnNm": "청량리",
            "subwayId": "1063",
            "subwayNm": "경의중앙선",
            "statnNmEng": null,
            "statnFid": null,
            "statnFnm": null,
            "statnTid": null,
            "statnTnm": null,
            "operPblinstt": null,
            "zipNo": null,
            "adresBass": null,
            "adresDetail": null,
            "telno": null,
            "fxnum": null,
            "directAt": null,
            "ord": "5",
            "subwayXcnts": "204244.2",
            "subwayYcnts": "453442.3",
            "trnsitCo": null,
            "subwayList": null,
            "pltfomSe": null,
            "gffDoor": null,
            "crosngAt": null,
            "toiletAt": null,
            "dspsnCvntlAt": null,
            "trttprkAt": null,
            "bcyclCstdyAt": null,
            "sctnTime": null,
            "sctnDstnc": null,
            "statnSn": null,
            "updnLine": null,
            "trainSttus": null,
            "lstcarAt": null,
            "imageX": "1768",
            "imageY": "668",
            "trainNo": null,
            "lastRecptnDt": null,
            "fixedDateTimeStr": null
        }
    ],
    "errorMessage": {
        "status": 200,
        "code": "INFO-000",
        "message": "정상 처리되었습니다.",
        "link": "",
        "developerMessage": "",
        "total": 10
    }
}

* */